from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer
)
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib.enums import TA_CENTER
from reportlab.lib.colors import HexColor

styles = getSampleStyleSheet()

title_style = styles["Heading1"]
title_style.alignment = TA_CENTER
title_style.textColor = HexColor("#FF7A00")

heading_style = styles["Heading2"]
heading_style.textColor = HexColor("#FF7A00")

normal_style = styles["BodyText"]


def add_heading(story, title):
    story.append(Paragraph(title, heading_style))
    story.append(Spacer(1, 8))


def generate_resume_pdf(data: dict, output_path: str):

    document = SimpleDocTemplate(
        output_path,
        topMargin=30,
        bottomMargin=30,
        leftMargin=40,
        rightMargin=40
    )

    story = []

    request = data["request"]
    resume = data["resume_content"]

    # ======================================================
    # Header
    # ======================================================

    story.append(
        Paragraph(
            request.get("name", "").upper(),
            title_style
        )
    )

    story.append(Spacer(1, 10))

    story.append(
        Paragraph(
            f"<b>Education:</b> {request.get('education', '')}",
            normal_style
        )
    )

    story.append(Spacer(1, 20))

    # ======================================================
    # Professional Summary
    # ======================================================

    add_heading(story, "Professional Summary")

    story.append(
        Paragraph(
            resume.get("professional_summary", ""),
            normal_style
        )
    )

    story.append(Spacer(1, 15))

    # ======================================================
    # Experience
    # ======================================================

    add_heading(story, "Professional Experience")

    for exp in resume.get("experience_bullets", []):

        story.append(
            Paragraph(
                f"• {exp}",
                normal_style
            )
        )

    story.append(Spacer(1, 15))

    # ======================================================
    # Skills
    # ======================================================

    add_heading(story, "Technical Skills")

    story.append(
        Paragraph(
            ", ".join(resume.get("skills", [])),
            normal_style
        )
    )

    story.append(Spacer(1, 15))

    # ======================================================
    # Projects
    # ======================================================

    add_heading(story, "Projects")

    for project in resume.get("project_descriptions", []):

        story.append(
            Paragraph(
                f"• {project}",
                normal_style
            )
        )

    story.append(Spacer(1, 15))

    # ======================================================
    # Certifications
    # ======================================================

    certifications = request.get("certifications", [])

    if certifications:

        add_heading(story, "Certifications")

        for cert in certifications:

            story.append(
                Paragraph(
                    f"• {cert}",
                    normal_style
                )
            )

        story.append(Spacer(1, 15))

    # ======================================================
    # Footer
    # ======================================================

    story.append(
        Paragraph(
            "<font color='#888888'><i>Generated by Enterprise AI Resume Generator</i></font>",
            normal_style
        )
    )

    document.build(story)